# Generated by Django 5.1.7 on 2025-08-29 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_card_carditem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carditem',
            old_name='img',
            new_name='image',
        ),
    ]
