# Generated by Django 5.1.7 on 2025-08-29 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_rename_img_carditem_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCarousel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ProductCarouselItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.TextField()),
                ('label', models.CharField(blank=True, max_length=200)),
                ('carousel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='store.productcarousel')),
            ],
        ),
    ]
