# Generated by Django 5.1.7 on 2025-08-29 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_productcarousel_productcarouselitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='carditem',
            name='price',
            field=models.DecimalField(decimal_places=2, default=9.99, max_digits=255),
        ),
    ]
