# Generated by Django 5.1.7 on 2025-08-29 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_carditem_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='carditem',
            name='name',
            field=models.CharField(default='Product', max_length=255),
        ),
    ]
