# Generated by Django 5.1.7 on 2025-08-29 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_carditem_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcarouselitem',
            name='name',
            field=models.CharField(default='Product', max_length=255),
        ),
        migrations.AddField(
            model_name='productcarouselitem',
            name='price',
            field=models.DecimalField(decimal_places=2, default=9.99, max_digits=255),
        ),
    ]
